# Generated by Django 6.0.1 on 2026-02-01 13:30

import django.db.models.deletion
import identify.models.user_manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی کاربر', primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='ایمیل کاربر', max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='فعال بودن اکامت')),
                ('is_staff', models.BooleanField(default=False, help_text='دسترسی به پنل ادمین')),
                ('is_superuser', models.BooleanField(default=False, help_text='دسترسی به همه سوپر ادمین')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ('-is_superuser', '-is_active', '-created_time'),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(blank=True, help_text='موبایل کاربر', max_length=15, null=True)),
                ('first_name', models.CharField(blank=True, help_text='نام کاربر', max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, help_text='نام خانوادگی', max_length=50, null=True)),
                ('display_name', models.CharField(blank=True, help_text='نام نمایشی', max_length=10, null=True)),
                ('profile_images', models.ImageField(blank=True, null=True, upload_to=identify.models.user_manager.save_document)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user__is_active', '-created_time'),
            },
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['is_active', 'email'], name='user_active_role_idx'),
        ),
    ]
