# Generated by Django 6.0.1 on 2026-02-02 13:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('site_name', models.CharField(help_text='نام سایت', max_length=100)),
                ('logo', models.ImageField(help_text='لوگوی سایت', upload_to='site/logo/')),
                ('favicon', models.ImageField(help_text='آیکون سایت', upload_to='site/favicon/')),
                ('phone', models.CharField(help_text='شماره تماس', max_length=20)),
                ('email', models.EmailField(help_text='ایمیل پشتیبانی', max_length=254)),
                ('address', models.TextField(help_text='آدرس دفتر')),
                ('instagram', models.URLField(blank=True, help_text='لینک اینستاگرام', null=True)),
                ('telegram', models.URLField(blank=True, help_text='لینک تلگرام', null=True)),
                ('linkedin', models.URLField(blank=True, help_text='لینک لینکدین', null=True)),
                ('copyright_text', models.CharField(help_text='متن کپی\u200cرایت', max_length=200)),
                ('about_short', models.TextField(blank=True, help_text='توضیح کوتاه درباره سایت', null=True)),
                ('main_color', models.CharField(default='#007bff', help_text='رنگ اصلی سایت', max_length=7)),
                ('secondary_color', models.CharField(default='#6c757d', help_text='رنگ ثانویه سایت', max_length=7)),
            ],
            options={
                'abstract': False,
                'indexes': [models.Index(fields=['created_time'], name='website_sit_created_0edfe3_idx'), models.Index(fields=['updated_time'], name='website_sit_updated_7dd84e_idx')],
            },
        ),
    ]
