# Generated by Django 6.0.1 on 2026-02-03 04:44

import website.models.site_data
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesetting',
            options={'ordering': ('created_time',)},
        ),
        migrations.RemoveIndex(
            model_name='sitesetting',
            name='website_sit_created_0edfe3_idx',
        ),
        migrations.RemoveIndex(
            model_name='sitesetting',
            name='website_sit_updated_7dd84e_idx',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone_factory',
            field=models.CharField(blank=True, help_text='شماره تماس', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone_sales',
            field=models.CharField(blank=True, help_text='شماره تماس', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='phone_support',
            field=models.CharField(blank=True, help_text='شماره تماس', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='address',
            field=models.TextField(blank=True, help_text='آدرس دفتر', null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='email',
            field=models.EmailField(blank=True, help_text='ایمیل پشتیبانی', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='favicon',
            field=models.ImageField(help_text='آیکون سایت', upload_to=website.models.site_data.upload_image_setting_site),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='logo',
            field=models.ImageField(help_text='لوگوی سایت', upload_to=website.models.site_data.upload_image_setting_site),
        ),
        migrations.AddIndex(
            model_name='sitesetting',
            index=models.Index(fields=['site_name'], name='website_sit_site_na_f3d0e6_idx'),
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='phone',
        ),
    ]
