# Generated by Django 6.0.1 on 2026-02-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_sitesetting_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
