# Generated by Django 6.0.1 on 2026-02-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_sitesetting_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='locations_url',
            field=models.URLField(blank=True, help_text='اندپوینت نقشه گوگل', null=True),
        ),
    ]
