# Generated by Django 6.0.1 on 2026-02-08 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_sitesetting_locations_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='economic_number',
            field=models.CharField(blank=True, help_text='شماره اقتصادی', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='standard_code',
            field=models.CharField(blank=True, help_text='کد قفل استاندارد', max_length=20, null=True),
        ),
    ]
