# Generated by Django 6.0.1 on 2026-02-09 12:23

import django.db.models.deletion
import uuid
import website.models.products
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_sitesetting_economic_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='نام رنگ', max_length=50)),
                ('code', models.CharField(help_text='کد رنگ (HEX یا نام)', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='فعال / غیرفعال')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('width', models.PositiveSmallIntegerField(blank=True, help_text='عرض', null=True)),
                ('height', models.PositiveSmallIntegerField(blank=True, help_text='ارتفاع', null=True)),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='عنوان واحد اندازه\u200cگیری (مثلاً سانتی\u200cمتر)', max_length=50)),
                ('symbol', models.CharField(help_text='نماد واحد (cm, mm, kg)', max_length=20)),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='عنوان دسته\u200cبندی', max_length=50, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='اسلاگ برای URL دسته\u200cبندی', unique=True)),
                ('image', models.ImageField(blank=True, help_text='تصویر دسته\u200cبندی', null=True, upload_to='categories')),
                ('is_active', models.BooleanField(default=True, help_text='فعال / غیرفعال')),
                ('parent', models.ForeignKey(blank=True, help_text='دسته\u200cبندی والد', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='website.categories')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='نام محصول', max_length=120, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, help_text='اسلاگ محصول برای URL', unique=True)),
                ('product_type', models.CharField(choices=[('door', 'درب آسانسور'), ('spare', 'قطعه یدکی')], help_text='نوع محصول', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='فعال / غیرفعال')),
                ('category', models.ManyToManyField(help_text='دسته\u200cبندی\u200cهای محصول', related_name='products', to='website.categories')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='CatalogProduct',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(blank=True, help_text='تصویر محصول', null=True, upload_to=website.models.products.upload_product_images)),
                ('is_primary', models.BooleanField(default=False, help_text='تصویر اصلی')),
                ('product', models.ForeignKey(help_text='محصول مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='catalog_files', to='website.product')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='تصویر محصول', upload_to=website.models.products.upload_product_images)),
                ('is_primary', models.BooleanField(default=False, help_text='تصویر اصلی')),
                ('product', models.ForeignKey(help_text='محصول مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='website.product')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('opening_type', models.CharField(blank=True, choices=[('Central', 'سانترال'), ('telescopic', 'تلسکوپی')], help_text='نوع بازشو (سانترال، تلسکوپی و …)', max_length=50)),
                ('direction_opening', models.CharField(blank=True, choices=[('left', 'چپ'), ('right', 'راست'), ('mid', 'وسط')], help_text='جهت باز شو', max_length=50, null=True)),
                ('material', models.CharField(blank=True, help_text='جنس متریال', max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='عنوان سئو (Google Title)', max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='توضیحات سئو (Meta Description)', max_length=160, null=True)),
                ('usage', models.CharField(blank=True, help_text='کاربرد (مسکونی، تجاری، بیمارستانی)', max_length=100)),
                ('fire_resistant', models.BooleanField(default=False, help_text='مقاوم در برابر حریق')),
                ('has_sensor', models.BooleanField(default=False, help_text='دارای سنسور ایمنی')),
                ('description', models.TextField(blank=True, help_text='توضیحات تکمیلی محصول')),
                ('color', models.ForeignKey(blank=True, help_text='رنگ محصول', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.color')),
                ('product', models.ForeignKey(help_text='محصول مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.product')),
                ('size', models.ForeignKey(blank=True, help_text='ابعاد محصول', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.size')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.AddField(
            model_name='size',
            name='unit',
            field=models.ForeignKey(help_text='واحد اندازه\u200cگیری', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.unit'),
        ),
    ]
