# Generated by Django 6.0.1 on 2026-02-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_color_size_unit_categories_product_catalogproduct_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='title',
            field=models.CharField(help_text='عنوان واحد اندازه\u200cگیری (مثلاً سانتی\u200cمتر)', max_length=50, unique=True),
        ),
    ]
