# Generated by Django 6.0.1 on 2026-02-09 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_unit_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogproduct',
            name='is_primary',
        ),
    ]
