# Generated by Django 6.0.1 on 2026-02-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_catalogproduct_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='berand',
            field=models.CharField(blank=True, choices=[('radplus', 'رادپلاس'), ('selecom_plus', 'سلکوم پلاس'), ('half_selcom', 'نیمه سلکوم'), ('asr', 'آریان سیستم رو')], help_text='برند محصول', max_length=50, null=True),
        ),
    ]
