# Generated by Django 6.0.1 on 2026-02-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_product_berand'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='lenght',
            field=models.PositiveSmallIntegerField(blank=True, help_text='طول', null=True),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='direction_opening',
            field=models.CharField(blank=True, choices=[('left', 'چپ باز شو'), ('right', 'راست باز شو'), ('mid', 'وسط باز شو')], help_text='جهت باز شو', max_length=50, null=True),
        ),
    ]
