# Generated by Django 6.0.1 on 2026-02-10 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_size_lenght_alter_productdetails_direction_opening'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='lenght',
            new_name='length',
        ),
    ]
