# Generated by Django 6.0.1 on 2026-02-10 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_rename_lenght_size_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='opening_type',
            field=models.CharField(blank=True, choices=[('Central', 'سانترال'), ('telescopic', 'تلسکوپی'), ('none', 'ندارد')], help_text='نوع بازشو (سانترال، تلسکوپی و …)', max_length=50),
        ),
    ]
