# Generated by Django 6.0.1 on 2026-02-10 08:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_productdetails_opening_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='عنوان کاربرد (مسکونی، تجاری، بیمارستانی)', max_length=100, unique=True)),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, help_text='نام محصول', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='کد قطعه یدکی', max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='وضعیت فعال بودن قطعه')),
                ('product', models.ForeignKey(help_text='محصولی که این قطعه مربوط به آن است', on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='website.product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('opening_type', models.CharField(blank=True, choices=[('Central', 'سانترال'), ('telescopic', 'تلسکوپی')], help_text='نوع بازشو (سانترال، تلسکوپی و …)', max_length=50)),
                ('direction_opening', models.CharField(blank=True, choices=[('left', 'چپ باز شو'), ('right', 'راست باز شو'), ('mid', 'وسط باز شو')], help_text='جهت باز شو', max_length=50, null=True)),
                ('material', models.CharField(blank=True, help_text='جنس متریال', max_length=100, null=True)),
                ('meta_title', models.CharField(blank=True, help_text='عنوان سئو (Google Title)', max_length=60, null=True)),
                ('meta_description', models.CharField(blank=True, help_text='توضیحات سئو (Meta Description)', max_length=160, null=True)),
                ('fire_resistant', models.BooleanField(default=False, help_text='مقاوم در برابر حریق')),
                ('has_sensor', models.BooleanField(default=False, help_text='دارای سنسور ایمنی')),
                ('description', models.TextField(blank=True, help_text='توضیحات تکمیلی محصول')),
                ('color', models.ForeignKey(blank=True, help_text='رنگ محصول', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.color')),
                ('product', models.ForeignKey(help_text='محصول مرتبط', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='website.product')),
                ('size', models.ForeignKey(blank=True, help_text='ابعاد محصول', null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.size')),
                ('usage', models.ManyToManyField(blank=True, help_text='کاربرد ها', to='website.usage')),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
        migrations.DeleteModel(
            name='ProductDetails',
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['created_time'], name='website_spa_created_af8d02_idx'),
        ),
        migrations.AddIndex(
            model_name='sparepart',
            index=models.Index(fields=['updated_time'], name='website_spa_updated_c8b1a9_idx'),
        ),
    ]
