# Generated by Django 6.0.1 on 2026-02-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_usage_remove_product_slug_alter_product_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='اسلاگ فیلد', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='door',
            name='title',
            field=models.CharField(blank=True, help_text='نام دقیق محصول', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='اسلاگ فیلد', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, help_text='اسلاگ فیلد', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='title',
            field=models.CharField(blank=True, help_text='عنوان قطعه یدکی', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, help_text='نام کلی محصول', max_length=100, null=True),
        ),
    ]
