# Generated by Django 6.0.1 on 2026-02-10 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_door_slug_door_title_product_slug_sparepart_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='door',
            name='leaf_count',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'تک\u200cلته'), (2, 'دولته'), (3, 'سه\u200cلته'), (4, 'چهارلته')], help_text='تعداد لته', null=True),
        ),
    ]
