# Generated by Django 6.0.1 on 2026-02-10 12:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_door_leaf_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='like',
            field=models.ManyToManyField(blank=True, help_text='کاربران کاربران که لایک کردن', related_name='like_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='un_like',
            field=models.ManyToManyField(blank=True, help_text='کاربران دیس لایک کرده اند', related_name='unlike_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ProductComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='ایدی', primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, help_text='نام ارسال\u200cکننده (برای کاربران مهمان)', max_length=100)),
                ('text', models.TextField(help_text='متن نظر')),
                ('is_approved', models.BooleanField(default=False, help_text='آیا توسط ادمین تأیید شده؟')),
                ('parent', models.ForeignKey(blank=True, help_text='کامنت والد (برای ریپلای)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='website.productcomment')),
                ('product', models.ForeignKey(help_text='محصول مربوطه', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='website.product')),
                ('user', models.ForeignKey(blank=True, help_text='کاربر ثبت\u200cنام شده', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_time',),
            },
        ),
    ]
