# Generated by Django 6.0.1 on 2026-02-11 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_product_like_product_un_like_productcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی محصول'),
        ),
    ]
