# Generated by Django 6.0.1 on 2026-02-11 17:42

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_sparepart_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='توضیح مختصر', null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='توضیحات تکمیلی محصول'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='text',
            field=ckeditor.fields.RichTextField(help_text='متن نظر'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='توضیحات تکمیلی محصول'),
        ),
    ]
