# Generated by Django 6.0.1 on 2026-02-12 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_categories_description_alter_door_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimages',
            name='is_active',
            field=models.BooleanField(default=True, help_text='فعال بودن'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='description',
            field=models.TextField(blank=True, help_text='توضیح مختصر', null=True),
        ),
        migrations.AlterField(
            model_name='door',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی محصول'),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='text',
            field=models.TextField(help_text='متن نظر'),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی محصول'),
        ),
    ]
