# Generated by Django 6.0.1 on 2026-02-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_productimages_is_active_alter_categories_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogproduct',
            name='is_active',
            field=models.BooleanField(default=True, help_text='فعال بودن'),
        ),
    ]
