# Generated by Django 6.0.1 on 2026-02-13 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_catalogproduct_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی محصول', max_length=500),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی محصول', max_length=500),
        ),
    ]
