# Generated by Django 6.0.1 on 2026-02-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_alter_door_description_alter_sparepart_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی محصول', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productcomment',
            name='text',
            field=models.TextField(help_text='متن نظر', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='description',
            field=models.TextField(blank=True, help_text='توضیحات تکمیلی محصول', max_length=1000),
        ),
    ]
