# Generated by Django 6.0.1 on 2026-02-17 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0022_alter_door_description_alter_productcomment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='door',
            name='usage',
            field=models.ManyToManyField(blank=True, help_text='کاربرد ها', related_name='doors', to='website.usage'),
        ),
    ]
