services:
  django-app:
    build:
      context: ../
      dockerfile: docker/django/Dockerfile
    image: website:v0.1
    volumes:
      - ../:/app

    env_file:
      - ../.env.prod

    ports:
      - "8000:8000"

    restart: always
