services:
    web:
        build:
            context: ../
            dockerfile: docker/nginx/Dockerfile
        ports:
            - "80:80"

        volumes:
            - static_files:/var/www/static/
            - media_files:/var/www/media/

        depends_on:
            - django-app
        
        restart: always
