services:
  redis:
    image: redis:8.0.4
    restart: always
    container_name: redis
    command: >
      redis-server
        --save ""
        --appendonly no
        --loglevel warning
    volumes:
      - redis_data:/data
